add copy  config.log
Signed-off-by: bvolovat <borisv@armosec.io>

diff --git a/.github/workflows/performance.yaml b/.github/workflows/performance.yaml
--- a/.github/workflows/performance.yaml
+++ b/.github/workflows/performance.yaml
@@ -187,3 +187,16 @@ jobs:
             kubectl apply -f -
           
           echo "Metrics collection job deployed with duration: ${{ github.event.inputs.DURATION_TIME }} minutes"
+
+      - name: Copy config.log to Kubernetes Pod
+        run: |
+          # Get the running pod for the job
+          POD_NAME=$(kubectl get pod -l job-name=metrics-test -n default -o jsonpath="{.items[0].metadata.name}")
+
+          if [ -z "$POD_NAME" ]; then
+            echo "ERROR: No pod found for the metrics-test job!"
+            exit 1
+          fi
+
+          echo "Copying config.log to $POD_NAME:/workspace/config.log"
+          kubectl cp logs/config.log default/$POD_NAME:/workspace/config.log
